### ISSUE TITLE
Allow for configuring Guzzle's verify option

### ISSUE THREAD

**Issue by kylestev** [laravel-notification-channels/webhook#12]
I'm hoping to raise a discussion on how to go about changing the [`'verify' => false`](https://github.com/laravel-notification-channels/webhook/blob/b649cbdff2af113fdedb4fbd35774f59d96e9459/src/WebhookChannel.php#L41) behavior present in the WebhookChannel code.

According to [the Guzzle docs](http://docs.guzzlephp.org/en/stable/request-options.html#verify):

>Set to false to disable certificate verification (_this is insecure!_).

(Emphasis mine)

**Comment by atymic** [comment]
Merged in #16
