### ISSUE TITLE
Laravel 5.6/5.7/5.8/6.0

### ISSUE THREAD

**Issue by gizburdt** [laravel-notification-channels/webhook#20]
Is it possible to update this package for Laravel 5.6/5.7? :)

There is already a PR for it.

**Comment by andrej-griniuk** [comment]
Second that.

**Comment by luchaos** [comment]
for some odd reason this was the _only_ package among 30 others that prevented a smooth laravel upgrade the last three times i did one - had to resort to others' repos each time.
which makes me wonder - are notification channels not the way to send arbitrary webhooks? i mean, it feels very convenient to use this system for webhooks as well but maybe i‘m missing something?

**Comment by gizburdt** [comment]
Yeah, same here! I don't want to hurt anybody, since it's open source. But it would be cool if this package could be updated!

**Comment by devinhyden** [comment]
Looks like I need to implement my own solution. :( I held off on migrating to 5.7 because of this and 5.8 is now out.

**Comment by oliverbj** [comment]
Would be really useful with 5.6, 5.7 and 5.8 support.

**Comment by miladnouri** [comment]
I forked it and added **Laravel 5.7 and 5.8 support**.
you can use it:
https://github.com/miladnouri/laravel-notification-webhook

**Comment by robinvdvleuten** [comment]
I've created a PR for it -> #26

**Comment by atymic** [comment]
Hey everyone!
Sorry for the delay. I'll check through the PRs in the next few days and we'll get it updated to work with all of the recent versions.

**Comment by hotmeteor** [comment]
@atymic Any update?

**Comment by atymic** [comment]
Sorry for the delay, have opened a PR :)
I'll merge it tomorrow unless there are any objections.
