### ISSUE TITLE
Channel Name

### ISSUE THREAD

**Issue by gizburdt** [laravel-notification-channels/webhook#30]
Hi,

Thanks for taking care of the issues and PR's!
I'm wondering for a long time; why is the channel name capitalized?

https://github.com/laravel-notification-channels/webhook/blob/master/src/WebhookChannel.php#L35

All other packages (and core packages) are using lowercase names.

Thanks :)

**Comment by atymic** [comment]
Good question!

I'm not sure why it's capitalized, but it's passed to `Str:Studly()` so it shouldn't matter anyway

https://github.com/laravel/framework/blob/1bbe5528568555d597582fdbec73e31f8a818dbc/src/Illuminate/Notifications/RoutesNotifications.php#L42-L44

Feel free to PR an update + a test if possible to cover it

**Comment by gizburdt** [comment]
I don't think it will break anything (https://github.com/laravel-notification-channels/webhook/blob/master/src/WebhookChannel.php#L35)

But maybe it's safe to - when we change it - bump the major version?

The reason I submitted this issue is because we save the notification route in the database (in our project) and later we check to which channels we need to push the notification. The only notification channel which is capitalized is this one. So we need an extra if statement to make it work properly.

**Comment by atymic** [comment]
Closed in #35, and will tag a new major version :)
