### ISSUE TITLE
On-Demand Notifications

### ISSUE THREAD

**Issue by lachlanhickey** [laravel-notification-channels/webhook#31]
Is there a method of using the WebHook function with the laravel 'on-demand' notification function?

Something like this? 
`Notification::route('webhook', 'HTTP-POST-URL')->notify(new SendSMS());`

**Comment by atymic** [comment]
That should work, are you having is with that?

**Comment by lachlanhickey** [comment]
Yes, it's just not posting. 

I'm not sure what I'm doing wrong. I have tried other laravel-notification-channels with this method successfully. 

I'm not getting anything posted to the URL, and no error either..

**Comment by atymic** [comment]
What did the issue end up being?

**Comment by lachlanhickey** [comment]
I have no idea @atymic . It just started working. Possibly something to do with my queues.

**Comment by lachlanhickey** [comment]
@atymic I'm having this issue again on laravel version 7, any thoughts?

**Comment by HamzaDevz** [comment]
Same issue here in laravel v7

**Comment by lachlanhickey** [comment]
@HamzaDevz try changing your casing on your code. In L7 it changes from an upper case 'Webook' to 'webhook'.

**From:**
`Notification::route('Webhook', 'HTTP-POST-URL')->notify(new SendSMS());`

**To:**
`Notification::route('webhook', 'HTTP-POST-URL')->notify(new SendSMS());`
