### ISSUE TITLE
Empty body

### ISSUE THREAD

**Issue by ilvalerione** [laravel-notification-channels/webhook#37]
Hi, 
I'm trying to use this channel, but the body of the post request generated via Guzzle steel empty.

This is my message: 

```php
WebhookMessage::create()
            ->data([
                'event' => 'My event name',
                'payload' => [
                    'foo' => 'bar',
                ],
            ])
            ->userAgent("Webhook-Notification-Channel")
            ->header('X-Signature', $notifiable->signature);
```

I'm passing a simple array in the `data` method that is a JSON-encodable value.

Anyone stumble in this behaviour?
Thanks

**Comment by dungnh** [comment]
@ilvalerione Did you resolve this issue? I'm getting the same issue. The requested data is an empty array.

**Comment by ilvalerione** [comment]
Hi @dungnh I extended the class to support multiple URLs so I rewrited the guzzle request by myself. I don't know if the original package works properly.

**Comment by dungnh** [comment]
Hi @ilvalerione , 
Thanks for your response. I saw that I need to add Content-Type to the header as Application/JSON like this: 
` ->header('Content-Type', 'application/json')`
