### ISSUE TITLE
throws a CouldNotSendNotification even though it was sent

### ISSUE THREAD

**Issue by luchaos** [laravel-notification-channels/webhook#7]
First of all - thanks for that package! Works really nice so far.

I use it to send discord webhook notifications as the other discord notification integration works via bots.
Discord answers with a 204 (no response body) instead of a 200 http status code which throws said exception.
I saw in the code that the check for that is an explicit http status code comparison - wouldn't it make sense to deem 2\* responses as successful in general?

In its current state notifications cause failed jobs with an empty exception message after being sent successfully.

```
NotificationChannels\Webhook\Exceptions\CouldNotSendNotification: Webhook responded with an error: `` in ...
```

**Comment by mpociot** [comment]
Thank you. Fixed :)

**Comment by luchaos** [comment]
Awesome - thanks for that quick fix!
